export const style1 = {
  paperContainer: {
    backgroundImage: `url(${"https://pembuatanvideo.com/wp-content/uploads/2021/07/Tahapan-pembuatan-video-company-profile_eps-production.jpg"})`,
    height: 550,
    width: "100%",
    align: "center",
    objectFit: "cover",
    boxShadow: 0,
  },
};
export const appbar = {
  one: {
    background: "#f2f2f2",
    color: "#999999",
    justifyContent: "center",
    height: 35,
  },
  two: { color: "#D6D6D6", height: 35, boxShadow: 0 },
};
export const styleButton = {
  bottonContainer: {
    background: "white",
    color: "#3333ff",
    width: "8rem",
    height: "2.5rem",
    mt: "2rem",
    fontSize: "0.7rem",
    fontWeight: 900,
    textTransform: "none",
    letterSpacing: 0.2,
    fontFamily: "system-ui",
    borderRadius: 0,
  },
};
export const bodyOne = {
  one: {
    pt: "150px",
    color: "white",
    fontSize: 18,
    fontFamily: "system-ui",
  },
  two: {
    fontWeight: 900,
    color: "white",
    mt: 3,
    fontFamily: "system-ui",
  },
  three: { fontWeight: 900, color: "white", fontFamily: "system-ui" },
};
export const bodyboxOne = {
  bottonOne: {
    textTransform: "none",
    color: "#3333ff",
    letterSpacing: 0,
    fontSize: 13,
    padding: 0,
  },
  bottonTwo: {
    textTransform: "none",
    color: "#3333ff",
    letterSpacing: 0,
    fontSize: 13,
    fontFamily: "system-ui",
    fontWeight: 900,
    mt: 8,
    ml: 2,
  },
  typeOne: {
    fontSize: 12,
    height: 100,
    width: "100%",
    color: "#999999",
    lineHeight: 1.5,
    letterSpacing: 0.3,
    padding: 3,
    fontFamily: "system-ui",
  },
  divDecor: {
    display: "flex",
    flexDirection: "row",
    background: "#1a1aff",
    width: "35%",
    height: 175,
    position: "absolute",
    top: "72rem",
    right: 230,
  },
  decor: {
    color: "#f2f2f2",
    marginLeft: 50,
    marginTop: 30,
    fontFamily: "system-ui",
  },
};
export const style2 = {
  paper2: {
    height: 350,
    width: "70%",
    borderRadius: 0,
    boxShadow: 0,
    mt: 4,
  },
};
export const bodyThree = {
  one: {
    width: "100%",
    background: "#f0f5f5",
    height: 580,
    display: "flex",
    justifyContent: "center",
  },
  two: {
    width: "50%",
    height: 450,
    objectFit: "fill",
  },
  three: {
    width: "50%",
  },
  four: {
    fontSize: 11,
    fontWeight: 800,
    color: "#3333ff",
    fontFamily: "system-ui",
  },
  five: {
    fontSize: 35,
    mt: 3,
    fontWeight: 800,
    fontFamily: "system-ui",
    color: "#201D1D",
  },
  six: {
    fontSize: 12,
    color: "#BCB6B6",
    width: "90%",
    mt: 3,
    fontFamily: "open-sans",
  },
  seven: {
    mt: 4,
    fontFamily: "system-ui",
    fontSize: 13,
    fontWeight: 600,
  },
};
export const bodyFour = {
  one: {
    fontFamily: "system-ui",
    fontWeight: 700,
    fontSize: 13,
    color: "#3333ff",
    letterSpacing: 0,
  },
  two: {
    width: "100%",
    height: 400,
    background: "white",
    display: "flex",
    justifyContent: "center",
  },
  three: {
    fontSize: 40,
    width: "80%",
    mt: 2.5,
    fontWeight: 700,
    fontFamily: "system-ui",
  },
  four: {
    background: "#3333ff",
    color: "#ffffff",
    width: "8rem",
    height: "2.5rem",
    mt: "1.5rem",
    fontSize: "0.7rem",
    fontWeight: 700,
    textTransform: "none",
    letterSpacing: 0.2,
    fontFamily: "system-ui",
    borderRadius: 0,
    transition: "none",
    webkitTapHighlightColor: "none",
  },
  five: {
    width: "100%",
    height: "100%",
  },
};
export const bodyFive = {
  one: {
    height: "900px",
    padding: 0,
    background: "rgb(240, 245, 245)",
    display: "flex",
    flexDirection: "column",
    mt: 8,
  },
  two: {
    width: "75%",
    display: "flex",
    flexDirection: "column",
    textAlign: "center",
  },
  three: {
    fontSize: 10,
    width: "90%",
    fontWeight: 700,
    color: "#DC0FC0",
  },
  four: {
    mt: 2,
    width: "90%",
    fontSize: 40,
    fontWeight: 700,
    fontFamily: "system-ui",
    color: "#20191F",
  },
  five: {
    width: "75%",
    height: 900,
    display: "flex",
    background: "rgb(240, 245, 245)",
    mt: 3,
  },
  six: {
    width: "75%",
    height: 900,
    display: "flex",
    background: "rgb(240, 245, 245)",
  },
  seven: {
    width: "65%",
    height: 360,
    background: "white",
    justifyContent: "center",
  },
  eight: { width: "65%", height: 360, background: "white", ml: 2.5 },
  nine: {
    width: 100,
    height: 100,
    align: "center",
  },
  ten: {
    width: "100%",
    height: 100,
    display: "flex",
    justifyContent: "center",
    marginTop: 60,
  },
  eleven: {
    background: "#E22FC8",
    color: "#ffffff",
    fontSize: 11,
    width: "35%",
    height: "30px",
    textDecoration: "none",
    borderBox: 0,
    borderRadius: 0,
    fontWeight: 700,
    alignItems: "center",
    mt: 2,
  },
  twelve: {
    width: "100%",
    height: "90%",
    mt: "5%",
    objectFit: "cover",
  },
  thirteen: {
    width: "95%",
    height: 260,
    background: "white",
    justifyContent: "center",
  },
  fourteen: {
    width: "100%",
    height: 100,
    display: "flex",
    justifyContent: "center",
    marginTop: 40,
  },
  fifteen: {
    background: "#3B42E4",
    color: "#ffffff",
    fontSize: 11,
    width: "45%",
    height: "30px",
    textDecoration: "none",
    borderBox: 0,
    borderRadius: 0,
    fontWeight: 700,
    alignItems: "center",
    mt: 2,
  },
};
export const bodySix = {
  one: {
    height: 460,
    width: "100%",
    background: "white",
  },
  two: {
    height: 480,
    display: "flex",
    flexDirection: "column",
  },
  three: {
    fontSize: 12,
    fontWeight: 700,
    fontFamily: "system-ui",
    textAlign: "center",
    color: "blue",
    mt: 6,
  },
  four: {
    fontSize: 40,
    fontWeight: 700,
    fontFamily: "system-ui",
    mt: 2,
    textAlign: "center",
  },
  five: {
    mt: 3,
    width: 90,
    height: 90,
    borderRadius: 20,
    objectFit: "cover",
  },
  six: {
    fontSize: 15,
    fontWeight: 600,
    fontFamily: "system-ui",
    textAlign: "center",
    display: "flex",
    justifyContent: "center",
    width: "50%",
    color: "#8C948B",
    mt: 3,
  },
  seven: {
    fontSize: 22,
    fontWeight: 700,
    fontFamily: "system-ui",
    mt: 2,
    textAlign: "center",
    color: "#474F46",
  },
  eight: {
    fontSize: 18,
    fontWeight: 600,
    fontFamily: "system-ui",
    mt: 1,
    textAlign: "center",
    color: "#8C948B",
  },
};
export const bodySeven = {
  one: {
    height: 550,
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  two: {
    width: "70%",
  },
  three: {
    textAlign: "center",
    fontSize: 10,
    fontWeight: 700,
    fontFamily: "system-ui",
    mt: 3,
    color: "blue",
  },
  four: {
    fontSize: 37,
    fontWeight: 900,
    fontFamily: "system-ui",
    mt: 1,
    textAlign: "center",
    color: "#262925",
  },
  five: {
    height: 75,
    display: "flex",

    justifyContent: "center",
  },
  six: {
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "system-ui",
    mt: 1,
    textAlign: "center",
    color: "#7D887A",
    width: "85%",
  },
  seven: {
    display: "flex",
    mt: 3,
    width: "80%",
  },
  eight: {
    width: "30%",
    height: 200,
    background: "#ffffff",
  },
  nine: {
    width: "100%",
    height: 70,
    display: "flex",
    justifyContent: "center",
    marginTop: 0,
  },
  ten: {
    width: 70,
    height: 70,
    align: "center",
  },
  eleven: {
    fontSize: 25,
    fontWeight: 800,
    fontFamily: "system-ui",
    textAlign: "center",
    color: "#2B2F2A",
  },
  twelve: {
    fontSize: 13,
    fontFamily: "system-ui",
    fontWeight: 600,
    color: "#7D887A",
    textAlign: "center",
    width: "90%",
    mt: 2,
  },
};
export const footer = {
  one: {
    background: "#121512",
    height: "55vh",
    display: "flex",
    justifyContent: "center",
  },
  two: {
    width: "15%",
    display: "flex",
    flexDirection: "column",
    color: "#E0E7E0",
    margin: 0,
    mt: 6.5,
  },
  three: {
    fontSize: 28,
    fontWeight: 700,
    margin: 0,
    fontFamily: "system-ui",
  },
  four: {
    fontFamily: "system-ui",
  },
  five: {
    display: "flex",
    mt: 2,
    fontFamily: "system-ui",
  },
  six: {
    mt: 0,
    fontFamily: "system-ui",
    textTransform: "none",
    color: "#E0E7E0",
    ml: 0,
    width: 120,
    textAlign: "end",
  },
  seven: {
    display: "flex",
    m: 0,
    mt: 2,
    width: 118,
    justifyContent: "center",
  },
};
